{% set name = "napari-plugin-engine" %}
{% set version = "0.1.9" %}
{% set sha256 = "5b504fe734c3f4df3a64a938982efc1b064b35e96e3e30f0b37a2cb5a2dd21c5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm
  run:
    - python >=3.6
    - importlib_metadata

test:
  imports:
    - napari_plugin_engine

about:
  home: https://github.com/napari/napari-plugin-engine
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A fork of pluggy - plugin management package
  doc_url: https://napari-plugin-engine.readthedocs.io/
  dev_url: https://github.com/napari/napari-plugin-engine
